In [1]:
import numpy as np

%matplotlib inline
from __future__ import print_function
from ipywidgets import interact, interactive, fixed
import ipywidgets as widgets
import matplotlib.pylab as plt
from IPython.display import clear_output, display, HTML
import scipy as sc
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pylab as plt

In [2]:
y = np.matrix('4; 8; 16; 32')
y

matrix([[ 4],
        [ 8],
        [16],
        [32]])

In [3]:
A = np.matrix('2; 4; 8; 16')
A

matrix([[ 2],
        [ 4],
        [ 8],
        [16]])

In [4]:
A.T

matrix([[ 2,  4,  8, 16]])

In [5]:
k = np.linalg.inv(A.T.dot(A))

In [6]:
k

matrix([[ 0.00294118]])

In [7]:
A.T

matrix([[ 2,  4,  8, 16]])

In [8]:
y

matrix([[ 4],
        [ 8],
        [16],
        [32]])

In [9]:
A.T

matrix([[ 2,  4,  8, 16]])

In [10]:
y

matrix([[ 4],
        [ 8],
        [16],
        [32]])

In [11]:
A.T.dot(y)

matrix([[680]])

In [12]:
l = A.T.dot(y)

In [13]:
w_ = k.dot(l)

In [14]:
w_

matrix([[ 2.]])

## 3 bilinmeyen

In [15]:
y = np.matrix('4; 15; 28; 39; 47')
A = np.matrix('1 2 1; 3 1 1; 4 12 3; 9 36 40; 11 8 8')
A

matrix([[ 1,  2,  1],
        [ 3,  1,  1],
        [ 4, 12,  3],
        [ 9, 36, 40],
        [11,  8,  8]])

In [16]:
k = np.linalg.inv(A.T.dot(A))
l = A.T.dot(y)

In [17]:
w_ = k.dot(l)
w_

matrix([[ 4.22736898],
        [ 1.16304719],
        [-1.025123  ]])

In [18]:
np.matrix('1 2 1').dot(w_)

matrix([[ 5.52834036]])

Dersteki Problem:

\begin{eqnarray}
\left(
\begin{array}{c}
2 \\ y_3 \\ 4 \\ 5 \\7 
\end{array}
\right)
\approx
\left(
\begin{array}{cc}
1 & y_0 \\ 2 & 1 \\ y_3 & 2 \\ 4 & y_3 \\ 5 & 4  
\end{array}
\right) 
\left(
\begin{array}{c}
 w_1 \\ w_2  
\end{array}
\right)
\end{eqnarray}

In [19]:
# Arbitrary values to start gradient decent.
y_0 = 1
y_3 = 3
w_1 = 5
w_2 = 7

#eta value
eta = 0.0006765

#gradient ascend limit
limit = 40000

#Defining functions to create matrix out of the currently changed variables
def create_y():
    return np.matrix('2; %s; 4; 5; 7' %(y_3))

def create_A():
    return np.matrix('1 %s; 2 1; %s 2; 4 %s; 5 4' %(y_0,y_3, y_3))
def create_w():
    return np.matrix('%s; %s' %(w_1,w_2))

y = create_y()
A = create_A()
w = create_w()
print(y)
print(A)
print(w)

[[2]
 [3]
 [4]
 [5]
 [7]]
[[1 1]
 [2 1]
 [3 2]
 [4 3]
 [5 4]]
[[5]
 [7]]


In [20]:
#Creating error matrix based on the current values
def create_error_matrix():
    y1 = create_y()
    A1 = create_A()
    w1 = create_w()
    return y1-(A1*w1)
e = create_error_matrix()
e

matrix([[-10],
        [-14],
        [-25],
        [-36],
        [-46]])

In [21]:
#Creating scalar value using error squares to identify error for gradient descend
def current_error():
    e1 = create_error_matrix()
    return e1.T*e1
current_error()

matrix([[4333]])

\begin{eqnarray}
0 & = & - A^\top y + A^\top A w^*  \\
A^\top y & = &  A^\top A w^* \\
w^* & = & (A^\top A)^{-1} A^\top y 
\end{eqnarray}

In [22]:
# Defining function to calculating w1 and w2 given the y0 and y3 values are optimal; using formula above ( minimizing error matrix using least squares approach)
def calculate_current_optimal_solution_matrix():
    y1 = create_y()
    A1 = create_A()
    k = np.linalg.inv(A1.T.dot(A1))
    l = A1.T.dot(y1)
    return k.dot(l)
   
calculate_current_optimal_solution_matrix()

matrix([[ 1.20833333],
        [ 0.20833333]])

In [23]:
print('Error before staring', current_error())
current_trend = 0 # 0 for decrease, 1 for increase. If current trend is decreasing then I subtract eta from unknown variables.
best_error = current_error()
best_y_0 = y_0
best_y_3 = y_3
best_w_1 = w_1
best_w_2 = w_2
for i in range(15000):
    error = current_error()
    if(current_trend == 0):
        y_0 = y_0 - eta
        y_3 = y_3 - eta
        w_1 = w_1 - eta
        w_2 = w_2 - eta
    else:
        y_0 = y_0 + eta
        y_3 = y_3 + eta
        w_1 = w_1 + eta
        w_2 = w_2 + eta
    new_error = current_error()
    #print('old error:' , error)
    #print('new error:', new_error)
    #print('best error:', best_error)
    #print('------------')
    if(new_error > error):
        # Error increased, changing trend
        if(current_trend == 0):
            current_trend = 1
        else:
            current_trend = 0
        #print('trend changed')
    if(new_error < best_error):
        best_error = new_error
        best_y_0 = y_0
        best_y_3 = y_3
        best_w_1 = w_1
        best_w_2 = w_2

print('Current error:' ,current_error())
print('Best error:' , best_error)
print('Found values after ', limit , ' iterations:')
print('y0 = ' , y_0 )
print('y3 = ' , y_3 )
print('w1 = ' , w_1 )
print('w2 = ' , w_2 )
print('Best values for equation:')
print('y0 = ' , best_y_0 )
print('y3 = ' , best_y_3 )
print('w1 = ' , best_w_1 )
print('w2 = ' , best_w_2 )

Error before staring [[4333]]
Current error: [[ 196.75167739]]
Best error: [[ 196.75167225]]
Found values after  40000  iterations:
y0 =  -3.862681999999838
y3 =  -1.8626819999998376
w1 =  0.13731800000019914
w2 =  2.1373180000002243
Best values for equation:
y0 =  -3.862005499999838
y3 =  -1.8620054999998377
w1 =  0.13799450000019914
w2 =  2.1379945000002243


In [24]:
#Now that we know optimal values for unknowns I solve the equation for optimal w1 and w2 given y0 and y3 values are correctly set.
calculate_current_optimal_solution_matrix()

matrix([[ 0.88728693],
        [ 0.27727768]])